language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - DB=MYSQL CORE_RELEASE=master

before_script:
    - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
    - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
    - cd ~/builds/ss

script:
    - vendor/bin/phpunit asset-gallery-field/tests/php
    - cd asset-gallery-field
    - nvm install 4.1
    - npm install
    - npm run test

branches:
    only:
        - master

matrix:
    allow_failures:
        - php: 7.0
